name: dspai
services:
  dev:
    image: mikesrnd/gpu-algo-dev:${IMAGE_TAG:-latest}
    pull_policy: missing    
    working_dir: /workspace/dspai
    volumes:
      - .:/workspace/dspai:cached
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - USERNAME=${USER:-$(whoami)}
      - USERID=${USER_ID:-1000}
      - GROUPID=${GROUP_ID:-1000}
    tty: true
    stdin_open: true
    entrypoint: ["/entrypoint.sh", "sleep", "infinity"]
